### ISSUE TITLE
FB Components for iOS Reports Usage of Ads

### ISSUE THREAD

**Issue by donchakkappan** [xamarin/FacebookComponents#141] opened 2019-08-29 06:11 UTC
Hi Folks

AppStore reports the presence of Advertising elements in our App , while trying to submit it for review.We are not using any Advertising elements in our App.

I tried to search the presence of "advertisingIdentifier" in the whole repo & got the results below

```
Binary file /mtouch-cache/FBSDKCoreKit.a matches
Binary file /device-builds/iphone10.2-12.3.2/mtouch-cache/FBSDKCoreKit.a matches
Binary file device-builds/iphone11.8-12.2/mtouch-cache/FBSDKCoreKit.a matches
```

How to resolve this issue.or , How to optionally disable the usage of Ads from FB SDK.

**Comment by bnoffer** [comment] 2019-11-06 12:55
@Redth @SotoiGhost 
I can confirm this issue with 5.6.0, with 4.4.0 we did not have that issue. Since we have to upgrade due to issue #154 with the old framework on the iOS 13 SDK we are now stuck, since we can not activate the IDFA for legal reasons.

From what I have read online this is due to the Audience Network component requiring the IDFA, perhaps it would be possible to make this optional?

See the following Stackoverflow posts for reference:
https://stackoverflow.com/questions/38845766/advertising-identifier-idfa-issue-when-submitting-the-app
https://stackoverflow.com/questions/21574680/app-rejected-because-of-advertisingidentifier-in-facebook-sdk-and-flurry-sdk

**Comment by Redth** [comment] 2019-11-06 13:15
I don’t see audience network in the dependency chain for Xamarin.Facebook.iOS but I do see marketing kit which maybe does it?  What if instead of referencing the top level package you pick just the dependencies from it you need directly?

**Comment by bnoffer** [comment] 2019-11-06 13:30
I will try and report back, because we only use the Login portion, but I do not have high hopes since LoginKit installs CoreKit as well and from what I can see CoreKit contains the reference.

**Comment by bnoffer** [comment] 2019-11-06 13:49
As expected, no success:
![Screenshot 2019-11-06 at 14 46 54](https://user-images.githubusercontent.com/9718314/68303634-89843180-00a4-11ea-8fe9-2e817785e4b0.png)

**Comment by bnoffer** [comment] 2019-11-07 10:02
I investigated further and it looks like there is a difference of the framework build between 4.40.0 and the 5.x.x versions. Inside the Facebook SDK the AdSupport framework is dynamically loaded in both cases. The question is if its an issue of the provided Cocoapod or of the build process of this project. I am not familiar enough with the cake system to provide a definitive answer to that.

**Comment by SotoiGhost** [comment] 2019-11-08 18:28
@bnoffer Looking at the FB code, it seems that CoreKit uses `AdSupport` framework in [`FBSDKAppEventsUtility.m`][1] file and looking at their [FAQ][2], I found the following question:

> **Does the Facebook SDK for iOS access the IDFA?**
> * The Facebook SDK includes code to access Apple’s Advertising Identifier (IDFA), but that code is only executed in certain situations.
> * The Facebook SDK for iOS only accesses IDFAs in the following scenarios: 1) if your app serves ads within the app through Facebook’s Audience Network, or 2) if your app logs app installs or other mobile App Events in order to attribute those events to your ad campaigns.
> * If you are not logging App Events (via the FBSDKAppEvents class), then the Facebook SDK is not accessing the IDFAs. Additionally, the Facebook SDK does not require AdSupport.framework to be included.
> * If you want to track App Events without collecting IDFA, you can disable IDFA collection within your app dashboard in the advanced setting section.

I was looking for the option on the dashboard but I cannot find it, I'll keep looking for the option but can you check if you fall in one of the scenarios stated above?

[1]: https://github.com/facebook/facebook-ios-sdk/blob/v5.6.0/FBSDKCoreKit/FBSDKCoreKit/AppEvents/Internal/FBSDKAppEventsUtility.m#L111
[2]: https://developers.facebook.com/docs/ios/troubleshooting?locale=en_US#IDFA

**Comment by SotoiGhost** [comment] 2019-11-08 18:51
I found the option. The option is under **Analytics** > **Settings** > First option.

![image](https://user-images.githubusercontent.com/5924210/68502542-43ef7200-0226-11ea-85dc-b5c03d85778e.png)

Sorry for the language, but I couldn't find the language option.

**Comment by bnoffer** [comment] 2019-11-11 10:42
It is fine, thank you. Yes you are correct, someone in our company turned that option on without our knowledge and it seems like that our app is now flagged by Apple for having used the Advertising Identifier.

Nevertheless thank you for your support.

**Comment by donchakkappan** [comment] 2019-12-06 08:04
@bnoffer Is it resolved now.

**Comment by bnoffer** [comment] 2019-12-06 12:15
The problem is that our App is flagged by Apple for using the IDFA now, therefore we are now submitting with the option selected that we served previous ads that used it.

**Comment by SotoiGhost** [comment] 2019-12-13 16:14
Closing this issue now, since the issue seems to be resolved. If you face something related to this, please, fill a new issue. Best!

**Closed by SotoiGhost** 2019-12-13 16:14 UTC
Labels: investigating
